engines:
  eslint:
    enabled: true
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - TODO
      - BUG
  csslint:
    enabled: true
  duplication:
    enabled: true
    exclude_fingerprints:
      - 05d115249180a440b6bba6248de73cbd
      - 853ac3c996858e81bca46613323fdc8e
    config:
      languages:
      - javascript
  markdownlint:
    enabled: true
  scss-lint:
    enabled: true
  shellcheck:
    enabled: false
ratings:
  paths:
  - src/**
  - "app.js"
exclude_paths:
- "test-client-e2e/"
- "test-client-e2e-angular1-deprecated/"
- "test-server-integration/"
- "test-server-unit/"
- "spec"
- "docs"
- "bin"
- "**/*.log"
