engines:
  eslint:
    enabled: true
    # ... CONFIG CONTENT ...
    checks:
      global-require: #Unexpected require()
        enabled: false
    # ... CONFIG CONTENT ...
  fixme:
    enabled: true
    config:
      strings:
      - FIXME
      - TODO
      - BUG
  csslint:
    enabled: true
  duplication:
    enabled: true
    exclude_fingerprints:
      - 05d115249180a440b6bba6248de73cbd
      - 853ac3c996858e81bca46613323fdc8e
    config:
      languages:
      - javascript
  markdownlint:
    enabled: true
    # ... CONFIG CONTENT ...
    checks:
      MD003: #Header style
        enabled: false
      MD012: #Multiple consecutive blank lines
        enabled: false
      MD013: #line length
        enabled: false
      MD024:
        enabled: false
      MD025: #Multiple top level headers in the same document
        enabled: false
      MD022: #Headers should be surrounded by blank lines
        enabled: false
      MD026: #Trailing punctuation in header
        enabled: false
    # ... CONFIG CONTENT ...
  scss-lint:
    enabled: true
  shellcheck:
    enabled: false
ratings:
  paths:
  - src/**
  - "app.js"
exclude_paths:
- "test-client-e2e/"
- "test-client-e2e-angular1-deprecated/"
- "test-integration/"
- "test-unit/"
- "test-util/"
- "spec"
- "docs"
- "bin"
- "**/*.log"
