language: node_js
node_js:
  - "7"
  - "6"
  - "6.0"
os:
  - linux # uses precise. I should update this to trusty
  - osx # uses 10.11. I should update this to 10.12 Sierra
dist: trusty # to use Ubuntu 14.04
#osx_image: xcode8.2 # to use macOS Sierra
sudo: required
env:
  global:
    - secure: tLyfM6pWEH04o6Sji0ROv1cwIRIU6P7ZNxS+j6ugp814U0LPtk9cwZdFtvne0rpPiOEkf93vUEsi8Y9OaCXVNwqe/6HnRSwNqzfWJ9nhAjHhsZ90zM0RLuBrE8zEEMiOoZyaoPsb3+NjhT5mjUyGrvFyiFoLYHK/R6hKANA3hyxKPthCdspLx5w0Kf21lZaur0aZiJAEYuaP81TR09lvr69Q5pTdGez0BaZt8Lxhsh/Y/RSyPZGlyOqwpyUhkkuWk3CXrfvfWk6EFXVeqLGP68Hh0WaHjiLIhHJZzPPkjKt4oTTtFkLaLh+jjWp3uCv/gF76pQuxqkEIxfxws9boCbCRfm741tOEMZJqc8wlmenCzqFNOqOiFU5qR9euVNRPaqzYyTGDG7Mi+uOAwNM3ctSDNagG6TXxIQgRIMstqvpG6vWvNDzjLIRRCV1iC5POMTW9Ejq60f2nlr3HyCKwpt0eaFK26R/rFfD/KXW967uMT2D5PR7WDurxcNuKfLBXCqYWF9bdkvKntkUjw/7+daxPSSWwgoA5GDnG3GwTWTAGSpKqn1YEe2A2ntCKXVP5k+QbBhBz9H/U2ONjyzHYkxXMHdhl9LeCfW2LVXFzkyjVOsQfXfCMr80F0XR0+hMHhfmU3Q0fxpogpdvBUITLu/WPjbhW2cKMfBz4yR1WgnQ= # CODECLIMATE
    - secure: W4cOrg/ziIRfws37WYboSPtcgz2nyF/f5fbSlJ0E0TG2uGLFLZAjNRWqxaPwvxFc8HmPoxeScvYGKmwhajbU2gcF/ZDuH9GtKt5+LKS/5W+Tw77oJMYTibFPukad6HrKV+kokefjmN8I+AZyiy6BYeqmEOG8UrzaObYn2tQAbxdxaNGz8u9W+DFgi3Gnpon8V5eCXRL3EvY8OhNxSLZbhPYDuQjY06/fchkGe6pb4GCwA2LnOBZZ6q3P57NentP+R525vLt/cQNmVxZde7A5iU8ZuLEC679mj2WNzedvg72E6JXa+iehp93mcZmtK2anohkbxAMxPN9oWFxGzcQYvXKjY1ci3MkG8m3nvHLbDcGEtW7FX3P7I02V6alrOV6rmFKCTarw8YgwnzAeB87EdB5RZajwI+vPjgZK2IrU46WHq5oMcoXkmjkBynSJIBgWSU0017I9IDP68zIEq/JCknfCflNp7mbDYAw1B0eqWJ+T/s0LoEFOhmJdC4BDWalco/AKJfGggUPYldxuwd8gJm1fUMmJ2XsXby7FBTiDIGZygdB44P6z2hoBiw1D9f/hzXurXVEngyxPRcvk+NbDsPvZWrfVl3gfmPmKvyqKyF/2v98FfX8FpBeLyGCpNQ+/k8n/n0owY0d0sghWRDnw1TeW7lYMN7WLPIQgatQLdfk= # COVERALLS
before_install:
  - source travisci/before_install.sh # use source to run it in the same shell
services:
  - mongodb
  - redis-server
before_script:
  - sleep 15 #https://docs.travis-ci.com/user/database-setup/#MongoDB-does-not-immediately-accept-connections
script:
  - bash travisci/travis_script.sh
after_success:
  - source travisci/after_success.sh # use source to run it in the same shell
cache:
  bundler: true
  directories:
    - node_modules
