language: node_js
sudo: required
node_js:
  - "7"
  - "6"
  - "6.0"
os:
  - linux
  #- osx
env:
  global:
    - secure: Rov9tYDaMYPBUeWDtD43S9h3llaljjMB0Khdi7P+kbkYOUPCm+Ol1Sr7nS+lwOQpF/3T1kva2OQ/LWkOM8kSng86EkMviEGQXpdlGRxP9clo8qmxyfbcKID5Q/a29kOIbkbbhx9cGFoepEjo+5T+Ya7GbbXIyMt1PNTCy5eLXnfU8BE/G3Ib8eVNBxGANiOuBTkKfzTyajH+pcsj0Wvr2Po/PjSIwYk6EfCzsYWbLDxjo86w7hD7F5OtjxPJTsYz3K1OwdneaUJ3bYLrGqpNewIfR4gASNTB4fBio0ZdBZ44UulKo6rO7tUMMQdCGm9+c54XeVGigJE9uhz8Fcim3FpfY9jraT9dhp5xPgvDl0OC/NVvHAGumak67X4Vkui5dAGGqbfNGfnWRvzkar/Xj3QpO7UJ0VEp2nFmZqgwE9CHhi+xMAh2+C5aoVsvtdb8LiACnN0YOfrMQvkoX2JGoGrLuJGJSTC3fRiLFIvWnX73L7+XKlrRUceoroyQ6WXEPkUbrtVtTN/yE0CVJmpVS1oE4Nre3zvOQAtIxGJWbk2rYTQ95C7cixAeo7ucFnX3J6YrSiTm0Ny+smdgv2KkXX8Q+UY0JG10BN3tHc67gqpvsaAPQaPGq4KF/jngE4a5H+skzpTnPRU0sozY4uNDXwGZmo4va03NFk6XVMk9rzo= # CODECLIMATE
    - secure: W4cOrg/ziIRfws37WYboSPtcgz2nyF/f5fbSlJ0E0TG2uGLFLZAjNRWqxaPwvxFc8HmPoxeScvYGKmwhajbU2gcF/ZDuH9GtKt5+LKS/5W+Tw77oJMYTibFPukad6HrKV+kokefjmN8I+AZyiy6BYeqmEOG8UrzaObYn2tQAbxdxaNGz8u9W+DFgi3Gnpon8V5eCXRL3EvY8OhNxSLZbhPYDuQjY06/fchkGe6pb4GCwA2LnOBZZ6q3P57NentP+R525vLt/cQNmVxZde7A5iU8ZuLEC679mj2WNzedvg72E6JXa+iehp93mcZmtK2anohkbxAMxPN9oWFxGzcQYvXKjY1ci3MkG8m3nvHLbDcGEtW7FX3P7I02V6alrOV6rmFKCTarw8YgwnzAeB87EdB5RZajwI+vPjgZK2IrU46WHq5oMcoXkmjkBynSJIBgWSU0017I9IDP68zIEq/JCknfCflNp7mbDYAw1B0eqWJ+T/s0LoEFOhmJdC4BDWalco/AKJfGggUPYldxuwd8gJm1fUMmJ2XsXby7FBTiDIGZygdB44P6z2hoBiw1D9f/hzXurXVEngyxPRcvk+NbDsPvZWrfVl3gfmPmKvyqKyF/2v98FfX8FpBeLyGCpNQ+/k8n/n0owY0d0sghWRDnw1TeW7lYMN7WLPIQgatQLdfk= # COVERALLS
  matrix:
    - JWT_SECRET=faketestjwt TWITTER_CONSUMER_KEY=consumerkey TWITTER_CONSUMER_SECRET=consumersecret TWITTER_CALLBACK_URL=http://127.0.0.1:3300/api/auth/twitter/callback FACEBOOK_APP_ID=appid FACEBOOK_APP_SECRET=appsecret FACEBOOK_CALLBACK_URL=http://localhost:3300/api/auth/facebook/callback GOOGLE_CLIENT_ID=clientid GOOGLE_CLIENT_SECRET=clientsecret GOOGLE_CALLBACK_URL=http://localhost:3300/api/auth/google/callback GITHUB_CLIENT_ID=clientid GITHUB_CLIENT_SECRET=clientsecret GITHUB_CALLBACK_URL=http://localhost:3300/api/auth/github/callback LINKEDIN_CLIENT_ID=clientid LINKEDIN_CLIENT_SECRET=clientsecret LINKEDIN_CALLBACK_URL=http://localhost:3300/api/auth/linkedin/callback USER_EMAIL=fake@fake.it PASS_EMAIL=fakepasswordemail RECAPTCHA_PUBLIC=recaptchapublic RECAPTCHA_SECRET=recaptchasecret NODE_ENV=test CI=yes
before_install:
  - source travisci/before_install.sh # use source to run it in the same shell
services:
  - mongodb
  - redis-server
before_script:
  - sleep 15 #https://docs.travis-ci.com/user/database-setup/#MongoDB-does-not-immediately-accept-connections
script:
  - bash travisci/travis_script.sh
after_success:
  - source travisci/after_success.sh # use source to run it in the same shell
cache:
  bundler: true
  directories:
    - node_modules
