version: 2
jobs:
  build:
    working_directory: /home/ubuntu/my-mean-website-server
    docker:
      - image: circleci/mongo:latest
      - image: node:7.9.0
        environment:
          NODE_ENV: test
          CI: yes
          JWT_SECRET: faketestjwt
          TWITTER_CONSUMER_KEY: consumerkey
          TWITTER_CONSUMER_SECRET: consumersecret
          TWITTER_CALLBACK_URL: http://127.0.0.1:3300/api/auth/twitter/callback
          FACEBOOK_APP_ID: appid
          FACEBOOK_APP_SECRET: appsecret
          FACEBOOK_CALLBACK_URL: http://localhost:3300/api/auth/facebook/callback
          GOOGLE_CLIENT_ID: clientid
          GOOGLE_CLIENT_SECRET: clientsecret
          GOOGLE_CALLBACK_URL: http://localhost:3300/api/auth/google/callback
          GITHUB_CLIENT_ID: clientid
          GITHUB_CLIENT_SECRET: clientsecret
          GITHUB_CALLBACK_URL: http://localhost:3300/api/auth/github/callback
          LINKEDIN_CLIENT_ID: clientid
          LINKEDIN_CLIENT_SECRET: clientsecret
          LINKEDIN_CALLBACK_URL: http://localhost:3300/api/auth/linkedin/callback
          USER_EMAIL: fake@fake.it
          PASS_EMAIL: fakepasswordemail
          RECAPTCHA_PUBLIC: recaptchapublic
          RECAPTCHA_SECRET: recaptchasecret
      - image: redis@latest
    steps:
      - checkout
      - run: echo "Starting..."
      - run: npm install
      - run: npm install pm2 -g
      - run: npm run docs
      - run: npm test
      - run: npm run nyc:threshold
#      - run: npm run codeclimate
#      - run: npm run coveralls